%YAML:1.0

#common parameters
savePath: "/root/LaserCamCal_ws/src/log/"
bag_path: "/root/LaserCameraCal_ws/src/CamLaserCalibraTool/rosbags/converted_all_sensors_no_exposure_v2.bag"

scan_topic_name: "/scan"
img_topic_name: "/camera/color/image_raw"

# tag info
tag_type: 1 # 1: kalibr_tag, 2: apriltag
tag_size: 0.031 # tag size, unit meter
tag_spacing: 0.29 # tag spacing, only used in kalibr_tag. For details, please see kalibr tag description.
black_border: 2 # if you use kalibr_tag black_boarder = 2; if you use apriltag black_boarder = 1

#camera calibration 
model_type: PINHOLE
camera_name: cam0
image_width: 640
image_height: 480

distortion_parameters:
   k1: 0.0
   k2: 0.0
   p1: 0.0
   p2: 0.0

projection_parameters:
   fx: 617.2950439453125
   fy: 617.333740234375
   cx: 324.6525573730469
   cy: 233.7224884033203

